In [32]:
import pandas as pd


df = pd.read_csv("E:\\FORMATION WCS\\PROJETS\PROJET3\\tennis_atp-master\\ATP_MASTER_tennis_single_depuis_1991_testalgo.csv", encoding='utf8', delimiter=',', low_memory=False)
df = df.iloc[:50000]
data = df

In [31]:
data.head()

tourney_id tourney_name surface  draw_size tourney_level tourney_date  \
0   1991-339     Adelaide    Hard         32             A   1990-12-31   
1   1991-339     Adelaide    Hard         32             A   1990-12-31   
2   1991-339     Adelaide    Hard         32             A   1990-12-31   
3   1991-339     Adelaide    Hard         32             A   1990-12-31   
4   1991-339     Adelaide    Hard         32             A   1990-12-31   

   match_num           score  best_of round  ...  player_2_rank  \
0          1  6-4 3-6 7-6(2)        3   R32  ...           56.0   
1          2  6-3 3-6 7-6(6)        3   R32  ...          304.0   
2          3         6-0 6-4        3   R32  ...           69.0   
3          4      7-6(2) 6-1        3   R32  ...           50.0   
4          5         7-5 6-3        3   R32  ...           88.0   

   player_1_rank_points  player_2_rank_points  player_1_seed  player_2_seed  \
0            891.847152           1422.612662            1.0            NaN   
1            891.847152           1422.612662            NaN            NaN   
2           1422.612662            891.847152            NaN            NaN   
3            891.847152           1422.612662            NaN            8.0   
4            891.847152           1422.612662            4.0            NaN   

                 winner                                     players    target  \
0        Magnus Larsson          ('Boris Becker', 'Magnus Larsson')  player_2   
1  Slobodan Zivojinovic  ('Mark Kratzmann', 'Slobodan Zivojinovic')  player_2   
2         Patrik Kuhnen         ('Patrik Kuhnen', 'Veli Paloheimo')  player_1   
3       Todd Woodbridge      ('Guillaume Raoux', 'Todd Woodbridge')  player_2   
4         Udo Riglewski         ('Sergi Bruguera', 'Udo Riglewski')  player_2   

   surface_enc  tourney_level_enc  
0            3                  0  
1            3                  0  
2            3                  0  
3            3                  0  
4            3                  0  

[5 rows x 56 columns]

In [143]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, recall_score, f1_score
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [144]:
lencoder = LabelEncoder()

data['surface_enc'] = lencoder.fit_transform(data['surface'])
data['tourney_level_enc'] = lencoder.fit_transform(data['tourney_level'])
data['player_1_enc'] = lencoder.fit_transform(data['player_1_name'])
data['player_2_enc'] = lencoder.fit_transform(data['player_2_name'])

In [145]:
# Features to be used in predictive models
# Will try five different classification models:
    # Gradient boosting
    # Random forest
    # Logistic regression
    # Support vector machine
    # Linear discriminant analysis

X = data[['surface_enc', 'tourney_level_enc', 'player_1_enc', 'player_2_enc']]

y = data['target']

In [161]:
data[['surface_enc', 'tourney_level_enc', 'player_1_enc', 'player_2_enc', 'winner', 'players']][data['winner'] == 'Abdelhak Hameurlaine']

surface_enc  tourney_level_enc  player_1_enc  player_2_enc  \
1481            1                  1             1           513   
9055            1                  1             1          1124   

                    winner                                       players  
1481  Abdelhak Hameurlaine         ('Abdelhak Hameurlaine', 'Jean Nabi')  
9055  Abdelhak Hameurlaine  ('Abdelhak Hameurlaine', 'Phillipe Ventura')

In [162]:
data[data['winner'] == 'Abdelhak Hameurlaine'].groupby('winner')['surface_enc'].count()

winner
Abdelhak Hameurlaine    2
Name: surface_enc, dtype: int64

In [168]:
data[data['winner'] == 'Phillipe Ventura'].groupby('winner')['surface_enc'].count()

winner
Phillipe Ventura    1
Name: surface_enc, dtype: int64

In [160]:
data.groupby('winner')['surface_enc'].count()

winner
Aaron Krickstein        134
Abdelhak Hameurlaine      2
Abou Berthe               1
Adam Malik               11
Adam Skrzypczak           3
                       ... 
Zack Fleishman            2
Zeljko Krajan             9
Zeljko Tosic              1
Zoran Sevcenko            2
Zulfiqar Ahmed            2
Name: surface_enc, Length: 1321, dtype: int64

In [147]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [148]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [149]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(C = 0.1, penalty= 'l2', solver= 'liblinear').fit(X_train,y_train)

In [169]:
# Bloc de saisie des noms des joueurs
# player1 = input("Nom du premier joueur : ")
# player2 = input("Nom du deuxième joueur : ")
# player1 = "Rafael Nadal"
# player2 = "Roger Federer"

# Encodage des variables pour les joueurs
# surface = input("Surface du match (ex: hard, clay, grass) : ")
# surface = "Clay"
# tourney_level = input("Niveau du tournoi (ex: G, M, A) : ")
# tourney_level = "G"
# surface_enc = lencoder.transform([surface])[0]
# tourney_level_enc = lencoder.fit_transform([tourney_level]).reshape(1,-1)


surface_inp = 0
tourney_level_inp = 3
player_1_inp = 1
player_2_inp = 1124


# surface_inp = lencoder.transform([surface_inp])[0]
# tourney_level_inp = lencoder.transform([tourney_level_inp])[0]
# player_1_inp = lencoder.transform([player_1_inp])[0]
# player_2_inp = lencoder.transform([player_2_inp])[0]


z = np.array([surface_inp, tourney_level_inp, player_1_inp, player_2_inp]).reshape(1, -1)
y_pred = model.predict(z)
print(y_pred)

['player_2']


In [128]:
print(surface_inp)

Clay


In [99]:
tourney_level_enc

array([[0]], dtype=int64)

In [97]:
surface_enc

array([0], dtype=int64)

In [111]:
print("score d'exactitude (accuracy) sur l'ensemble d'entraînement :",model.score(X_train, y_train))
print("score d'exactitude (accuracy) sur l'ensemble de test :",model.score(X_test, y_test))

score d'exactitude (accuracy) sur l'ensemble d'entraînement : 0.50656
score d'exactitude (accuracy) sur l'ensemble de test : 0.49792


In [102]:
from sklearn.metrics import confusion_matrix
pd.DataFrame(data = confusion_matrix(y_true = y_test, y_pred = model.predict(X_test)),
             index = model.classes_ + " ACTUAL",
             columns = model.classes_ + " PREDICTED")

player_1 PREDICTED  player_2 PREDICTED
player_1 ACTUAL                 749                5467
player_2 ACTUAL                 809                5475

In [106]:
from sklearn.model_selection import GridSearchCV

# Définir les valeurs de paramètres à tester
param_grid = {'C': [0.1, 1, 10],
              'penalty': ['l1', 'l2'],
              'solver': ['liblinear', 'saga']}
# gs_params = {'C': 10**np.linspace(-2, 2, 26)}

grid_search = GridSearchCV(model, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)


# Afficher les meilleurs paramètres et le score de précision
print("Meilleurs paramètres:", grid_search.best_params_)
print("Score de précision:", grid_search.best_score_)

Meilleurs paramètres: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
Score de précision: 0.5072000000000001


## ANCIEN CODE THEO ARCHIVE

In [20]:
player1_data = 356 
player2_data = 267

# Prédiction
player1_data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(1, -1)
player2_data = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(1, -1)
player1_data = scaler.transform(player1_data)
player2_data = scaler.transform(player2_data)
winner = nb.predict(np.concatenate([player1_data, player2_data]))

print("Le gagnant prédit est : ", winner[0])

c:\Users\theob\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\theob\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Le gagnant prédit est :  1018


In [31]:
ok=df[df['winner_name'].str.contains("Djo")]
ok


surface  draw_size  tourney_date  winner_id     winner_name  winner_ht  \
135216    Clay         32      20040913     104925  Novak Djokovic      188.0   
135566  Carpet          4      20040409     104925  Novak Djokovic      188.0   
136449  Carpet         48      20051031     104925  Novak Djokovic      188.0   
136465  Carpet         48      20051031     104925  Novak Djokovic      188.0   
136537  Carpet         32      20051024     104925  Novak Djokovic      188.0   
...        ...        ...           ...        ...             ...        ...   
188428    Hard        128      20230116     104925  Novak Djokovic      188.0   
188438    Hard        128      20230116     104925  Novak Djokovic      188.0   
188443    Hard        128      20230116     104925  Novak Djokovic      188.0   
188446    Hard        128      20230116     104925  Novak Djokovic      188.0   
188447    Hard        128      20230116     104925  Novak Djokovic      188.0   

        winner_age  loser_id  loser_ht  loser_age  best_of  minutes  w_ace  
135216        17.3    103096     173.0       26.7        3    146.0    4.0  
135566        16.8    108912       NaN       20.6        3      NaN    NaN  
136449        18.4    103812     198.0       24.2        3     19.0    1.0  
136465        18.4    103264     180.0       27.1        3    105.0   12.0  
136537        18.4    103672     175.0       24.8        3    105.0    4.0  
...            ...       ...       ...        ...      ...      ...    ...  
188428        35.6    105777     188.0       31.6        5    187.0   11.0  
188438        35.6    200282     183.0       23.9        5    126.0    4.0  
188443        35.6    126094     188.0       25.2        5    123.0   14.0  
188446        35.6    126205     185.0       25.6        5    140.0   12.0  
188447        35.6    126774     193.0       24.4        5    176.0    7.0  

[1057 rows x 13 columns]

In [2]:
import pandas as pd
dg=pd.read_csv("C:\\Users\\theob\\Desktop\\Wild\\P3\\bdd_tennis_single_concat.csv",usecols=["winner_id","loser_id","surface","winner_name","draw_size", "tourney_date", "winner_age", "winner_ht","loser_age", "loser_ht", "best_of", "minutes", "w_ace"])

de=dg[dg['winner_name']== 'Roger Federer']['winner_id']

# id Nadal =104775
#id Federer= 103819



In [4]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, recall_score, f1_score
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
df=pd.read_csv("C:\\Users\\theob\\Desktop\\Wild\\P3\\bdd_tennis_single_concat.csv",usecols=["winner_id","loser_id","surface","winner_name","draw_size", "tourney_date", "winner_age", "winner_ht","loser_age", "loser_ht", "best_of", "minutes", "w_ace"])

player1 = "Alexander Zverev"
player2 = "Novak Djokovic"
scaler = StandardScaler()
data = pd.read_csv(
    "C:\\Users\\theob\\Desktop\\Wild\\P3\\bdd_tennis_single_concat.csv",
    usecols=[
        "winner_id",
        "loser_id",
        "surface",
        "winner_name",
        "loser_name",
        "draw_size",
        "tourney_date",
        "winner_age",
        "winner_ht",
        "loser_age",
        "loser_ht",
        "best_of",
        "minutes",
        "w_ace",
    ],
)
data = data[
    ((data["winner_name"] == player1) & (data["loser_name"] == player2))
    | ((data["winner_name"] == player2) & (data["loser_name"] == player1))
]
le = LabelEncoder()
data["surface"] = le.fit_transform(data["surface"])
data["winner_name"] = le.fit_transform(data["winner_name"])
data = data.fillna(data.mean())

matches = data
if matches.empty:
    print(f"No matches found between {player1} and {player2}.")
    exit()

id_j1=df[df['winner_name']== player1]['winner_id'].values[0]
id_j2=df[df['winner_name']== player2]['winner_id'].values[0]
print("idJ1=",id_j1)
print("idJ2=",id_j2)
#FEDERER= 103819
#Nadal= 104745

X_matches = matches[
    ["draw_size", "surface", "tourney_date", "winner_age", "winner_ht", "loser_age", "loser_ht", "minutes", "w_ace"]
]
y_matches = matches["winner_name"]


scaler.fit(X_matches)
X_matches = scaler.transform(X_matches)
nb = GaussianNB()
nb.fit(X_matches, y_matches)

J1= data[data['winner_id']== id_j1]['winner_name'].values[0]
print("J1=",J1)
J2= data[data['winner_id']== id_j2]['winner_name'].values[0]
print("J2=",J2)

player1_data = data.loc[data["winner_name"] == J1]
if player1_data.empty:
    print(f"Le joueur {player1} n'a pas été trouvé dans la base de données.")
    exit()
player1_data = player1_data[
    [
        "draw_size",
        "surface",
        "tourney_date",
        "winner_age",
        "winner_ht",
        "loser_age",
        "loser_ht",
        "minutes",
        "w_ace",
    ]
]

# Rechercher les données du joueur 2 dans le dataframe

player2_data = data.loc[data['winner_name'] == J2]
if player2_data.empty:
    print(f"Le joueur {player2} n'a pas été trouvé dans la base de données.")
    exit()
player2_data = player2_data[["draw_size", "surface", "tourney_date", "winner_age", "winner_ht", "loser_age", "loser_ht", "minutes", "w_ace"]]


player1_data = scaler.transform(player1_data)
player2_data = scaler.transform(player2_data)
# Prédiction
winner = nb.predict(np.concatenate([player1_data, player2_data]))
print("Le gagnant prédit est : ", le.inverse_transform(winner)[0])


100644
J1= 0
Le gagnant prédit est :  Alexander Zverev


C:\Users\theob\AppData\Local\Temp\ipykernel_776\3026058377.py:39: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data = data.fillna(data.mean())


In [89]:
#joueurs ayant le plus de victoire à Rolland-Garros
df[df.tourney_name.str.contains("arros")]['winner_name'].value_counts()

Rafael Nadal           112
Novak Djokovic          86
Roger Federer           73
Guillermo Vilas         58
Ivan Lendl              53
                      ... 
Mark Knowles             1
Zan Guerry               1
Frederik Fetterlein      1
Donald Johnson           1
Ilya Ivashka             1
Name: winner_name, Length: 1037, dtype: int64

In [90]:
# Le plus de Victoire sur terrain GRASS
df[df['surface']== 'Grass']['winner_name'].value_counts()

Roger Federer        194
Jimmy Connors        174
John Newcombe        162
Phil Dent            158
Stan Smith           154
                    ... 
Fernando Meligeni      1
A Jackson              1
A Ferguson             1
German Puentes         1
Yuki Bhambri           1
Name: winner_name, Length: 1700, dtype: int64

In [91]:
df[df['winner_name'].str.contains('Federer')][['winner_age','tourney_name']]

winner_age   tourney_name
115478        17.1       Toulouse
115487        17.1       Toulouse
116234        17.4      Marseille
116250        17.4      Marseille
116462        17.5      Rotterdam
...            ...            ...
184035        39.8  Roland Garros
184111        39.8      Wimbledon
184151        39.8      Wimbledon
184171        39.8      Wimbledon
184181        39.8      Wimbledon

[1265 rows x 2 columns]

In [92]:
dFed=df[df['winner_name'].str.contains('Federer')]
dFed['w_ace'].mean()

7.915481171548117

In [93]:
df["w_svpt"].mean()

78.09945562948242

In [94]:
dFed=df[df['winner_name'].str.contains('Federer')]
dFed['winner_hand'].unique()

array(['R'], dtype=object)

In [95]:
#=> Calculer le taux de victoire des droitiers contre gauchers et réciproques 

dg=df[(df['winner_hand']=='L') & (df['loser_hand']=='R')]
dg.shape

(23307, 49)

In [96]:
dg=df[(df['winner_hand']=='R') & (df['loser_hand']=='L')]
dg.shape

(21301, 49)

In [97]:
de=df[df['winner_name'].str.contains("Federer")]["winner_ht"].unique()
de

array([185.])

In [98]:
dt=df['loser_ht'].value_counts()
dt

185.0    24660
183.0    24152
188.0    21800
180.0    20715
190.0    14080
178.0    13040
193.0    10399
175.0     9785
173.0     5904
196.0     4830
170.0     2922
198.0     2475
191.0     1165
201.0      902
168.0      700
203.0      627
172.0      375
208.0      346
206.0      309
181.0      164
163.0      118
194.0       99
211.0       84
186.0       68
174.0       33
160.0       30
179.0       25
165.0       21
176.0       11
189.0       10
182.0        5
Name: loser_ht, dtype: int64

In [99]:
df['best_of'].unique()

array([3, 5, 1], dtype=int64)

In [100]:
df['round'].unique()

array(['R32', 'R16', 'QF', 'SF', 'F', 'R64', 'R128', 'RR', 'BR', 'ER'],
      dtype=object)

In [101]:
df['draw_size'].unique()

array([ 32,  16,  64, 128,  96,   4,   8,   6,  10,   5,   9,   7,  24,
        48,  12,   2,  56,  28,  18], dtype=int64)

In [102]:
df['winner_ioc'].value_counts()

USA    39022
ESP    15564
AUS    15008
FRA    11867
GER     9085
       ...  
UAE        2
TJK        1
MNE        1
GUM        1
RHO        1
Name: winner_ioc, Length: 128, dtype: int64

In [112]:
#df['winner_age']= df['winner_age'].dropna()

df['winner_age'].round(1) # arrondir la colonne à 1 décimale
df['winner_age'].value_counts()


TypeError: unsupported operand type(s) for *: 'method' and 'float'